test: frontend unit test 작성
vc2team-code-typing-practice/frontend pull request #56
Opened 2022-06-21 13:28 UTC by Ravender91

## 코드를 작성한 이유

- 기본적인 프론트엔드 유닛테스트를 작성해보았습니다.

## 무엇이 변하였는가

- 리덕스 목업 슬라이스를 사용한 renderTest 유틸함수가 추가되었습니다. firebase mock을 사용하지 않고 slice의 목업 데이터를 사용하여 테스트를 진행하였습니다.

## 작성한 코드에 문제점이 존재하는가

- firebase mock을 통해 로그인 테스트 등 여러가지를 진행해보고 싶었는데, 아직 제대로 된 방법을 찾지 못하였습니다. 

## 리뷰 중점사항 

- 좀 더 추가했으면 하는 테스트, 다른 여러 테스트들을 팀원들과 더 상의해보겠습니다. 변수명, 파일이름 등 피드백 부탁드립니다.

2022-06-21 13:51 UTC, Pogith approved these changes
수고하셨습니다!

2022-06-21 16:40 UTC, dongtimes2 requested changes
package.json에서 사용하지 않는 디펜던시 들은 모두 다 지워주시기 바랍니다.

2022-06-21 17:06 UTC, Ravender91 commented
> 

넵 수정했습니다.

2022-06-22 06:59 UTC, dongtimes2 approved these changes
고생하셨습니다.

2022-06-22 07:35 UTC, merged